[metadata]
name = tgable
version = attr: tgable.__version__
author = Roman Valov
author_email = roman.valov@gmail.com
description = alternative strict typing aiogram dispatcher
url = https://github.com/chatio-ai/tgable
license =
classifiers =

[options]
install_requires = file: requirements.txt
package_dir =
    = src

[options.extras_require]
dev = file: requirements.dev.txt
